//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galactic_Tools_V2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galactic_Tools_V2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1200px_7ziplogo_svg_1_128x129 {
            get {
                object obj = ResourceManager.GetObject("1200px-7ziplogo.svg_1_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1200px_Yuzu_Emulator_SVG_svg_190x168 {
            get {
                object obj = ResourceManager.GetObject("1200px-Yuzu_Emulator_SVG.svg_190x168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _144_1448377_logo_ubisoft_logo_png_transparent_png_128x129 {
            get {
                object obj = ResourceManager.GetObject("144-1448377_logo-ubisoft-logo-png-transparent-png_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _212_2122682_obs_studio_logo_1_logo_obs_studio_128x129 {
            get {
                object obj = ResourceManager.GetObject("212-2122682_obs-studio-logo-1-logo-obs-studio_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _24_249964_blizzard_transparent_battle_net_battle_net_logo_png_128x129 {
            get {
                object obj = ResourceManager.GetObject("24-249964_blizzard-transparent-battle-net-battle-net-logo-png_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _24_249964_blizzard_transparent_battle_net_battle_net_logo_png_128x1291 {
            get {
                object obj = ResourceManager.GetObject("24-249964_blizzard-transparent-battle-net-battle-net-logo-png_128x1291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4ca3bc4d28e97fe9f36f755458733449 {
            get {
                object obj = ResourceManager.GetObject("4ca3bc4d28e97fe9f36f755458733449", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4ca3bc4d28e97fe9f36f755458733449_1_161x154 {
            get {
                object obj = ResourceManager.GetObject("4ca3bc4d28e97fe9f36f755458733449_1_161x154", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4ca3bc4d28e97fe9f36f755458733449_1_161x154_1_128x129 {
            get {
                object obj = ResourceManager.GetObject("4ca3bc4d28e97fe9f36f755458733449_1_161x154_1_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4ca3bc4d28e97fe9f36f755458733449_1_161x154_1_128x1291 {
            get {
                object obj = ResourceManager.GetObject("4ca3bc4d28e97fe9f36f755458733449_1_161x154_1_128x1291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4ca3bc4d28e97fe9f36f755458733449_100x100 {
            get {
                object obj = ResourceManager.GetObject("4ca3bc4d28e97fe9f36f755458733449_100x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4ca3bc4d28e97fe9f36f755458733449_100x1001 {
            get {
                object obj = ResourceManager.GetObject("4ca3bc4d28e97fe9f36f755458733449_100x1001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4ca3bc4d28e97fe9f36f755458733449_100x1002 {
            get {
                object obj = ResourceManager.GetObject("4ca3bc4d28e97fe9f36f755458733449_100x1002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _519_5198145_bluestacks_icon_bluestacks_logo_png_190x168 {
            get {
                object obj = ResourceManager.GetObject("519-5198145_bluestacks-icon-bluestacks-logo-png_190x168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6118379_128x129 {
            get {
                object obj = ResourceManager.GetObject("6118379_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6118379_128x1291 {
            get {
                object obj = ResourceManager.GetObject("6118379_128x1291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _70e902945f52904d0fdd033d7500877d {
            get {
                object obj = ResourceManager.GetObject("70e902945f52904d0fdd033d7500877d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _718475_social_media_new_instagram_logo_png_transparent_background {
            get {
                object obj = ResourceManager.GetObject("718475_social-media-new-instagram-logo-png-transparent-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _718475_social_media_new_instagram_logo_png_transparent_background_1_128x129 {
            get {
                object obj = ResourceManager.GetObject("718475_social-media-new-instagram-logo-png-transparent-background_1_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7570476 {
            get {
                object obj = ResourceManager.GetObject("7570476", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7d17aa00_a0ad_11e9_8e26_92efee03c9d3_128x129 {
            get {
                object obj = ResourceManager.GetObject("7d17aa00-a0ad-11e9-8e26-92efee03c9d3_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7d17aa00_a0ad_11e9_8e26_92efee03c9d3_128x1291 {
            get {
                object obj = ResourceManager.GetObject("7d17aa00-a0ad-11e9-8e26-92efee03c9d3_128x1291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _882px_Epic_Games_logo_128x129 {
            get {
                object obj = ResourceManager.GetObject("882px-Epic_Games_logo_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _97c418f388a3079c1b83959341795548 {
            get {
                object obj = ResourceManager.GetObject("97c418f388a3079c1b83959341795548", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _97c418f388a3079c1b839593417955481 {
            get {
                object obj = ResourceManager.GetObject("97c418f388a3079c1b839593417955481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Accover_211x257 {
            get {
                object obj = ResourceManager.GetObject("Accover_211x257", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap anydesk_for_mac_128x129 {
            get {
                object obj = ResourceManager.GetObject("anydesk-for-mac_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap anydesk_for_mac_128x1291 {
            get {
                object obj = ResourceManager.GetObject("anydesk-for-mac_128x1291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap anydesk_for_mac_128x1292 {
            get {
                object obj = ResourceManager.GetObject("anydesk-for-mac_128x1292", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apple_settings_1_493162__1_ {
            get {
                object obj = ResourceManager.GetObject("apple-settings-1-493162 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apple_settings_1_493162__1_1 {
            get {
                object obj = ResourceManager.GetObject("apple-settings-1-493162 (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud_Force_1_1_190x168 {
            get {
                object obj = ResourceManager.GetObject("Cloud_Force_1_1_190x168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CtrlTab_159_2_128x129 {
            get {
                object obj = ResourceManager.GetObject("CtrlTab_159-2_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CtrlTab_159_2_128x1291 {
            get {
                object obj = ResourceManager.GetObject("CtrlTab_159-2_128x1291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d9qp2p7_1a0f9cc6_26b2_4c73_8636_850ba731d191_128x129 {
            get {
                object obj = ResourceManager.GetObject("d9qp2p7-1a0f9cc6-26b2-4c73-8636-850ba731d191_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap defaultLogo_190x168 {
            get {
                object obj = ResourceManager.GetObject("defaultLogo_190x168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__10_ {
            get {
                object obj = ResourceManager.GetObject("download (10)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__3_ {
            get {
                object obj = ResourceManager.GetObject("download (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__3_1 {
            get {
                object obj = ResourceManager.GetObject("download (3)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__5_ {
            get {
                object obj = ResourceManager.GetObject("download (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__5_1 {
            get {
                object obj = ResourceManager.GetObject("download (5)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_file_explorer_icon_from_windows_10_build_18298_file_explorer_png_256_256 {
            get {
                object obj = ResourceManager.GetObject("download-file-explorer-icon-from-windows-10-build-18298-file-explorer-png-256_256" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ed4ca193fcdf72b005b170f1042c369d_190x168 {
            get {
                object obj = ResourceManager.GetObject("ed4ca193fcdf72b005b170f1042c369d_190x168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FC_New_Dawn_cover_art_211x257 {
            get {
                object obj = ResourceManager.GetObject("FC_New_Dawn_cover_art_211x257", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fdsff_190x168 {
            get {
                object obj = ResourceManager.GetObject("fdsff_190x168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_explorer_folder_libraries_icon_18298 {
            get {
                object obj = ResourceManager.GetObject("file-explorer-folder-libraries-icon-18298", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_explorer_folder_libraries_icon_182981 {
            get {
                object obj = ResourceManager.GetObject("file-explorer-folder-libraries-icon-182981", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Firefox_logo {
            get {
                object obj = ResourceManager.GetObject("Firefox_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Firefox_logo_128x129 {
            get {
                object obj = ResourceManager.GetObject("Firefox_logo_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Firefox_logo_128x1291 {
            get {
                object obj = ResourceManager.GetObject("Firefox_logo_128x1291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Galactic_tools_190x168 {
            get {
                object obj = ResourceManager.GetObject("Galactic_tools_190x168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gm_3ca57bb6_cab6_4224_98cd_4cdf8f5d38ea_cyberpunk2077 {
            get {
                object obj = ResourceManager.GetObject("gm-3ca57bb6-cab6-4224-98cd-4cdf8f5d38ea-cyberpunk2077", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Google_Chrome_icon__2011_ {
            get {
                object obj = ResourceManager.GetObject("Google_Chrome_icon_(2011)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons8_Windows_8_User_Interface_Command_Line_1_128x129 {
            get {
                object obj = ResourceManager.GetObject("Icons8-Windows-8-User-Interface-Command-Line-1_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoonlightLogo {
            get {
                object obj = ResourceManager.GetObject("MoonlightLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New_bruh {
            get {
                object obj = ResourceManager.GetObject("New bruh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New_bruh_128x129 {
            get {
                object obj = ResourceManager.GetObject("New_bruh_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New_bruh_128x1291 {
            get {
                object obj = ResourceManager.GetObject("New_bruh_128x1291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap opera_gx_browser_logo_icon_152976_128x129 {
            get {
                object obj = ResourceManager.GetObject("opera_gx_browser_logo_icon_152976_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap opera_gx_browser_logo_icon_152976_128x1291 {
            get {
                object obj = ResourceManager.GetObject("opera_gx_browser_logo_icon_152976_128x1291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap opera_gx_browser_logo_icon_152976_128x1292 {
            get {
                object obj = ResourceManager.GetObject("opera_gx_browser_logo_icon_152976_128x1292", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap picture13348385186152 {
            get {
                object obj = ResourceManager.GetObject("picture13348385186152", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_citra_nintendo_3ds_emulator_video_game_pokemon_logo_food_orange_190x168 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-citra-nintendo-3ds-emulator-video-game-pokemon-logo-food-orange_190x1" +
                        "68", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerISO_128x129 {
            get {
                object obj = ResourceManager.GetObject("PowerISO_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RPCS3_LOGO_190x168 {
            get {
                object obj = ResourceManager.GetObject("RPCS3_LOGO_190x168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SatrixTools_Server_Icon_Remake_1_190x168 {
            get {
                object obj = ResourceManager.GetObject("SatrixTools_Server_Icon_Remake_1_190x168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap steam_logo_transparent {
            get {
                object obj = ResourceManager.GetObject("steam-logo-transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap steam_logo_transparent_1_128x129 {
            get {
                object obj = ResourceManager.GetObject("steam-logo-transparent_1_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap steam_logo_transparent_1_128x1291 {
            get {
                object obj = ResourceManager.GetObject("steam-logo-transparent_1_128x1291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap steam_logo_transparent_128x129 {
            get {
                object obj = ResourceManager.GetObject("steam-logo-transparent_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TeamViewer_Logo_512x512 {
            get {
                object obj = ResourceManager.GetObject("TeamViewer_Logo_512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TeamViewer_Logo_512x512_128x129 {
            get {
                object obj = ResourceManager.GetObject("TeamViewer_Logo_512x512_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unknown {
            get {
                object obj = ResourceManager.GetObject("unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unknown_190x168 {
            get {
                object obj = ResourceManager.GetObject("unknown_190x168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unknown_190x168__1_ {
            get {
                object obj = ResourceManager.GetObject("unknown_190x168 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unknown2 {
            get {
                object obj = ResourceManager.GetObject("unknown2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Xenia_Emulator_Upadted_Logo_190x168 {
            get {
                object obj = ResourceManager.GetObject("Xenia_Emulator_Upadted_Logo_190x168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZortosUnzipper_32512_1_128x129 {
            get {
                object obj = ResourceManager.GetObject("ZortosUnzipper_32512-1_128x129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
